services:
  taskweb:
    build: .
    restart: unless-stopped
    ports:
      - "38000:38000"
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/app/data
